### ISSUE TITLE
Png Icons are not loading after cloning repository or Downloading Repository as Zip FIle

### ISSUE THREAD

**Issue by sharoseali** [Neogoma/metadata-tutorial#3]
HI Thanks for your great work. I have cloned this repo. And open the project in Unity. After loading the scene,  I observed that icons saved as PNG files in the project were not opening. I investigated and found. Even they are not opening in my OS. I am using Ubuntu 20.04. I tried both cloning and zip-loading. Is this issue happened to all?

My other Unity project icons are displayed when they open both inside and outside the editor. I don't know if the issue is on my side or something else.
@handrianj

**Comment by handrianj** [comment]
Hi, please try to clone again?

We had a problem with git lfs on some of our repos but it seems solved now.

Regards

**Comment by sharoseali** [comment]
hi @handrianj  Thanks for replaying. I have retried cloning both via git clone and manual ZIP download, but unfortunately the same issue persists. 
![pngIcon](https://github.com/Neogoma/metadata-tutorial/assets/19869426/25b66f70-9f93-428a-b229-1b944ec32805)

**Comment by handrianj** [comment]
Hi, can you try again ? We just cloned the repository in our devices using github desktop and we found no issue with the png files
